FROM node:18-alpine

WORKDIR /app

# RUN npx create-react-app . --template typescript, at first time run this to create react application first

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]